[package]
name = "my-app"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
color-eyre = { workspace = true }

[dev-dependencies]
anyhow = "1"
